# src/swagger.yaml
openapi: 3.0.0
info:
  title: Wanderlust Travel API
  version: 1.0.0
  description: REST API for managing hotels and users

paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
  /hotels:
    get:
      summary: Get all hotels
      responses:
        '200':
          description: A list of hotels
