openapi: 3.0.0
info:
  title: Wanderlust Travel API
  version: 1.0.0
  description: RESTful API for a travel agency to manage hotel listings and user authentication

servers:
  - url: http://localhost:5000

paths:
  /auth/register:
    post:
      summary: Register a new travel agency operator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - signUpCode
              properties:
                username:
                  type: string
                password:
                  type: string
                signUpCode:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Missing fields
        '401':
          description: Invalid sign up code
        '409':
          description: User already exists

  /auth/login:
    post:
      summary: Login as travel agency operator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful with JWT
        '401':
          description: Invalid credentials

  /hotels:
    get:
      summary: Get list of available hotels
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of hotels

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
